/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package frame;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author ABDUL MOIZ
 */
public class frame extends javax.swing.JFrame {

    /**
     * Creates new form frame
     */
        
       public void resetfields(){
        id.setText("");
        name.setText("");
        catogry.setSelectedIndex(0);
        Price.setText("");
       wsprice.setText("");
        contity.setText("");
    }

     void setproductlist(){
        String url ="jdbc:mysql://127.0.0.1:3306/db";
        String user="root";
        String password="";
        String qry="Select * from product";

        DefaultTableModel model =(DefaultTableModel) Productlist.getModel();
        model.setRowCount(0);
           
        try {
            // TODO code application logic here
            Class.forName("com.mysql.cj.jdbc.Driver");
            Connection con = DriverManager.getConnection(url, user, password) ;
           Statement smt=con.createStatement();
           ResultSet rs=smt.executeQuery(qry);
           while(rs.next()){
            Object[] cols=new Object[6];
            cols[0]=rs.getString("id");
            cols[1]=rs.getString("name");
            cols[2]=rs.getString("catagory");
            cols[3]=rs.getString("contity");
            cols[4]=rs.getString("price");
            cols[5]=rs.getString("wsPrice");
            model.addRow(cols);
        }
           smt.close();
           con.close();
           
        } catch (ClassNotFoundException ex) {
       System.out.print(ex.getMessage());
        } catch (SQLException ex) {
        System.out.print(ex.getMessage());
        }
        
       
        
        
        }
    public frame() {
        initComponents();
         setproductlist();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        searchtext = new javax.swing.JTextField();
        searchbtn = new javax.swing.JButton();
        Editbtn = new javax.swing.JButton();
        Deletebtn = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        id = new javax.swing.JTextField();
        name = new javax.swing.JTextField();
        catogry = new javax.swing.JComboBox<>();
        contity = new javax.swing.JTextField();
        Price = new javax.swing.JTextField();
        wsprice = new javax.swing.JTextField();
        AddProd = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        Productlist = new javax.swing.JTable();
        jLabel7 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBounds(new java.awt.Rectangle(80, 100, 0, 0));
        setUndecorated(true);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        searchtext.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchtextActionPerformed(evt);
            }
        });
        searchtext.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                searchtextKeyPressed(evt);
            }
        });
        getContentPane().add(searchtext, new org.netbeans.lib.awtextra.AbsoluteConstraints(85, 116, 235, 23));

        searchbtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pos/assit/magnifying-glass.png"))); // NOI18N
        searchbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchbtnActionPerformed(evt);
            }
        });
        getContentPane().add(searchbtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(338, 116, -1, -1));

        Editbtn.setText("Edit");
        Editbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EditbtnActionPerformed(evt);
            }
        });
        getContentPane().add(Editbtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 151, -1, 46));

        Deletebtn.setText("Delete");
        Deletebtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DeletebtnActionPerformed(evt);
            }
        });
        getContentPane().add(Deletebtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(291, 151, -1, 46));

        jPanel1.setBackground(new java.awt.Color(25, 34, 47));

        id.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                idActionPerformed(evt);
            }
        });

        catogry.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "None", "Snacks", "Fruits", "Dairy ", "Baking", "sea Food", "Toys ", " ", " " }));
        catogry.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                catogryActionPerformed(evt);
            }
        });

        contity.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                contityActionPerformed(evt);
            }
        });

        Price.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PriceActionPerformed(evt);
            }
        });

        AddProd.setText("Add");
        AddProd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddProdActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Product ID");

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Name");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Catgory");

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Contity");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Price");

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("WoleSale Price");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(34, 34, 34)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(wsprice, javax.swing.GroupLayout.PREFERRED_SIZE, 215, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(name, javax.swing.GroupLayout.PREFERRED_SIZE, 215, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(catogry, javax.swing.GroupLayout.PREFERRED_SIZE, 215, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(id, javax.swing.GroupLayout.PREFERRED_SIZE, 215, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(contity, javax.swing.GroupLayout.PREFERRED_SIZE, 215, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Price, javax.swing.GroupLayout.PREFERRED_SIZE, 215, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1)
                            .addComponent(jLabel4)
                            .addComponent(jLabel2)
                            .addComponent(jLabel6)
                            .addComponent(jLabel3)
                            .addComponent(jLabel5)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(104, 104, 104)
                        .addComponent(AddProd, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(34, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(id, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(8, 8, 8)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(name, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(catogry, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(4, 4, 4)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(contity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(8, 8, 8)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Price, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(wsprice, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(AddProd)
                .addContainerGap(14, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 209, -1, 400));

        jPanel2.setBackground(new java.awt.Color(25, 34, 47));

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setText("POINT OF SALE SYSTEM");
        jLabel8.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 4, true));

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pos/assit/left-arrow (1).png"))); // NOI18N
        jButton2.setText("Exit");
        jButton2.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(400, 400, 400)
                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 307, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(373, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(37, 37, 37)
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(9, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1180, -1));

        Productlist.setAutoCreateRowSorter(true);
        Productlist.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.lightGray, java.awt.Color.lightGray, java.awt.Color.lightGray, java.awt.Color.lightGray));
        Productlist.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        Productlist.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "ID", "Name", "Catgory", "Contity", "Price", "Wole sale price"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.Integer.class, java.lang.Long.class, java.lang.Long.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        Productlist.setSelectionForeground(new java.awt.Color(255, 255, 255));
        Productlist.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ProductlistMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(Productlist);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 150, 750, -1));

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pos/assit/wp2508260.jpg"))); // NOI18N
        jLabel7.setText("jLabel7");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1180, 630));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void searchbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchbtnActionPerformed
        // TODO add your handling code here:
        if(!searchtext.getText().isEmpty()){
        DefaultTableModel model=(DefaultTableModel) Productlist.getModel();
       String url ="jdbc:mysql://127.0.0.1:3306/db";
        String user="root";
        String password="";
       String serch= searchtext.getText();
        String qry;
         qry="select *from product where name="+"'"+serch+"';";
        try {
            // TODO code application logic here
            Class.forName("com.mysql.cj.jdbc.Driver");
            Connection con = DriverManager.getConnection(url, user, password) ;
           Statement smt=con.createStatement();
           ResultSet rs= smt.executeQuery(qry);
           while(rs.next()){
               
               model.setRowCount(0);
                Object[] cols=new Object[6];
            cols[0]=rs.getString("id");
            cols[1]=rs.getString("name");
            cols[2]=rs.getString("catagory");
            cols[3]=rs.getString("contity");
            cols[4]=rs.getString("price");
            cols[5]=rs.getString("wsPrice");
            model.addRow(cols);
           }
           smt.close();
           con.close();
           
        } catch (ClassNotFoundException ex) {
       System.out.print(ex.getMessage());
        } catch (SQLException ex) {
        System.out.print(ex.getMessage());
        }
        }
        else{
             setproductlist();
             
        }
    }//GEN-LAST:event_searchbtnActionPerformed

    private void searchtextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchtextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_searchtextActionPerformed

    private void EditbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EditbtnActionPerformed
        // TODO add your handling code here:
        if(!id.getText().isEmpty()&&
            !name.getText().isEmpty()&&
            !catogry.getSelectedItem().toString().isEmpty()&&
            !contity.getText().isEmpty()&&
            !Price.getText().isEmpty()&&
            !wsprice.getText().isEmpty()){
            
             int ID=Integer.parseInt(id.getText());
            int Contity=Integer.parseInt(contity.getText());
            String Catagory=catogry.getSelectedItem().toString();
            double price=Double.parseDouble(Price.getText());
            double wsPrice=Double.parseDouble(wsprice.getText());
            String Name = name.getText();
                 String url ="jdbc:mysql://127.0.0.1:3306/db";
        String user="root";
        String password="";
        String qry;
qry="update product set name="+"'"+Name+"',"+"catagory="+"'"+Catagory+"',"+"contity="+Contity+",price="+price+",wsprice="+wsPrice+" where id="+ID+";";
        try {
            // TODO code application logic here
            Class.forName("com.mysql.cj.jdbc.Driver");
            Connection con = DriverManager.getConnection(url, user, password) ;
           Statement smt=con.createStatement();
                int rows=smt.executeUpdate(qry);
                if(rows>0){
                    System.out.print("Row inserted");
                }
           
           smt.close();
           con.close();
           
        } catch (ClassNotFoundException ex) {
       System.out.print(ex.getMessage());
        } catch (SQLException ex) {
        System.out.print(ex.getMessage());
        }
        
       
    setproductlist();
          resetfields();
        }
        else{
             JOptionPane.showMessageDialog(null, "Fill the Entir field");
                  }
    }//GEN-LAST:event_EditbtnActionPerformed

    private void DeletebtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DeletebtnActionPerformed
        // TODO add your handling code here:
        if(!id.getText().isEmpty()&&
            !name.getText().isEmpty()&&
            !catogry.getSelectedItem().toString().isEmpty()&&
            !contity.getText().isEmpty()&&
            !Price.getText().isEmpty()&&
            !wsprice.getText().isEmpty())
        {
            int ID=Integer.parseInt(id.getText());
            int Contity=Integer.parseInt(contity.getText());
            String Catagory=catogry.getSelectedItem().toString();
            double price=Double.parseDouble(Price.getText());
            double wsPrice=Double.parseDouble(wsprice.getText());
            String Name = name.getText();
                 String url ="jdbc:mysql://127.0.0.1:3306/db";
        String user="root";
        String password="";
            String  qry="delete from product where id="+ID+";";

        try {
            // TODO code application logic here
            Class.forName("com.mysql.cj.jdbc.Driver");
            Connection con = DriverManager.getConnection(url, user, password) ;
           Statement smt=con.createStatement();
                int rows=smt.executeUpdate(qry);
                if(rows>0){
                    System.out.print("Row inserted");
                }
           
           smt.close();
           con.close();
           
        } catch (ClassNotFoundException ex) {
       System.out.print(ex.getMessage());
        } catch (SQLException ex) {
        System.out.print(ex.getMessage());
        }
        
       
    setproductlist();

                      resetfields();
                  }
        else{
             JOptionPane.showMessageDialog(null, "Fill the Entir field");
        }

        
    }//GEN-LAST:event_DeletebtnActionPerformed

    private void idActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_idActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_idActionPerformed

    private void catogryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_catogryActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_catogryActionPerformed

    private void contityActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_contityActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_contityActionPerformed

    private void PriceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PriceActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_PriceActionPerformed

    private void AddProdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddProdActionPerformed
        // TODO add your handling code here:
        if(!id.getText().isEmpty()&&
            !name.getText().isEmpty()&&
            !catogry.getSelectedItem().toString().isEmpty()&&
            !contity.getText().isEmpty()&&
            !Price.getText().isEmpty()&&
            !wsprice.getText().isEmpty()){
            int ID=Integer.parseInt(id.getText());
            int Contity=Integer.parseInt(contity.getText());
            String Catagory=catogry.getSelectedItem().toString();
            double price=Double.parseDouble(Price.getText());
            double wsPrice=Double.parseDouble(wsprice.getText());
            String Name = name.getText();
                 String url ="jdbc:mysql://127.0.0.1:3306/db";
        String user="root";
        String password="";
        String qry;
qry="insert into product value("+ID+","+"'"+Name+"'"+","+"'"+Catagory+"'"+","+Contity+","+price+","+wsPrice+");";
        try {
            // TODO code application logic here
            Class.forName("com.mysql.cj.jdbc.Driver");
            Connection con = DriverManager.getConnection(url, user, password) ;
           Statement smt=con.createStatement();
                int rows=smt.executeUpdate(qry);
                if(rows>0){
                    System.out.print("Row inserted");
                }
           
           smt.close();
           con.close();
           
        } catch (ClassNotFoundException ex) {
       System.out.print(ex.getMessage());
        } catch (SQLException ex) {
        System.out.print(ex.getMessage());
        }
        
       
    setproductlist();
          resetfields();
        }
        else{
             JOptionPane.showMessageDialog(null, "Fill the Entir field");
        }
        
    }//GEN-LAST:event_AddProdActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        this.dispose();

    }//GEN-LAST:event_jButton2ActionPerformed

    private void ProductlistMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ProductlistMouseClicked
        // TODO add your handling code here:
        DefaultTableModel model=(DefaultTableModel) Productlist.getModel();
        int index=Productlist.getSelectedRow();
        id.setText(model.getValueAt(index,0).toString());
        name.setText(model.getValueAt(index, 1).toString());
        catogry.setSelectedItem(model.getValueAt(index, 2).toString());
        contity.setText(model.getValueAt(index, 3).toString());
        Price.setText(model.getValueAt(index, 4).toString());
        wsprice.setText(model.getValueAt(index, 5).toString());
    }//GEN-LAST:event_ProductlistMouseClicked

    private void searchtextKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_searchtextKeyPressed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_searchtextKeyPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AddProd;
    private javax.swing.JButton Deletebtn;
    private javax.swing.JButton Editbtn;
    private javax.swing.JTextField Price;
    private javax.swing.JTable Productlist;
    private javax.swing.JComboBox<String> catogry;
    private javax.swing.JTextField contity;
    private javax.swing.JTextField id;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField name;
    private javax.swing.JButton searchbtn;
    private javax.swing.JTextField searchtext;
    private javax.swing.JTextField wsprice;
    // End of variables declaration//GEN-END:variables
}
